name: dry-logger
codacy_id: 5aae4837b97044cfa4537f083ad584e9
gemspec:
  authors: ["Luca Guidi"]
  email: ["me@lucaguidi.com"]
  summary: "Logging for Ruby"
  runtime_dependencies:
    - ["dry-core", ">= 1.0.0.rc1", "< 2"]
  development_dependencies:
    - rspec
