name: dry-logger
codacy_id: 5aae4837b97044cfa4537f083ad584e9
gemspec:
  authors: ["Luca Guidi"]
  email: ["me@lucaguidi.com"]
  summary: "Logging for Ruby"
  runtime_dependencies:
    - ["dry-core", "~> 0.5"]
  development_dependencies:
    - bundler
    - rake
    - rspec
